import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ComposedChart, Line, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowUpRight, BarChart3, Download, Info } from 'lucide-react';
import type { ScenarioResult } from '../../../packages/core/src';
import { csv, download, money, num } from '../lib';

const color = ['#3c8068', '#dc9946', '#7c9fba', '#b4a27e', '#9b809e', '#609c97', '#cc8770', '#747fa0'];
const tip = { border: '1px solid #dce1d5', borderRadius: 10, fontSize: 12, boxShadow: '0 4px 20px #213d2910' };
export function CostCurve({ result, selectedQ }: { result: ScenarioResult; selectedQ: number }) {
  const data = result.costCurve.map(d => ({ ...d, band: [d.p05, d.p95] }));
  return <section className="card chart-card"><div className="chart-heading"><div><span className="eyebrow">THE COST OF CAPACITY</span><h2>Find the balance</h2></div><span className="pill">Fixed fleet planning</span></div><p className="chart-description">Too little capacity leaves orders unassigned. Too much pays for idle capacity.</p><div className="chart-container"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{ top: 18, right: 18, left: 3, bottom: 20 }}><CartesianGrid vertical={false} stroke="var(--chart-grid)" strokeDasharray="3 5"/><XAxis dataKey="q" type="number" domain={['dataMin', 'dataMax']} tickLine={false} axisLine={false} fontSize={10} tickFormatter={v => num(v)} label={{ value: 'Private capacity (deliveries / day)', position: 'insideBottom', offset: -12, fontSize: 10, fill: 'var(--muted)' }}/><YAxis tickLine={false} axisLine={false} width={52} fontSize={10} tickFormatter={v => `${num(v / 1000, 1)}k`} label={{ value: 'R$ / day', position: 'insideTopLeft', dy: -25, fontSize: 10, fill: 'var(--muted)' }}/><Tooltip contentStyle={tip} labelFormatter={v => `${num(+v)} private slots`} formatter={(v, name) => [Array.isArray(v) ? `${money(+v[0])}–${money(+v[1])}` : money(+v), name === 'cost' ? 'Expected total cost' : '5–95% supply interval']}/><Area type="monotone" dataKey="band" fill="#dce9dc" fillOpacity={0.55} stroke="none" name="Supply interval"/><Line type="monotone" dataKey="cost" stroke="#38745b" strokeWidth={2.5} dot={false} isAnimationActive={false}/><ReferenceLine x={result.fixedQ} stroke="#38745b" strokeDasharray="4 4" label={{ value: `Q = ${num(result.fixedQ)}`, position: 'insideTopRight', fill: '#38745b', fontSize: 10 }}/>{selectedQ !== result.fixedQ && <ReferenceLine x={selectedQ} stroke="#dc9946" strokeDasharray="4 4" label={{ value: 'Your fleet', position: 'insideTopLeft', fontSize: 10 }}/>}</ComposedChart></ResponsiveContainer></div><div className="chart-foot"><span><span className="line-key"/> Expected cost <i className="band-key"/> 5–95% across supply</span><button className="icon-button" title="Download cost curve CSV" aria-label="Download cost curve CSV" onClick={() => download('fleet-lab-cost-curve.csv', csv([['private_capacity', 'expected_daily_cost', 'p05_supply_cost', 'p95_supply_cost'], ...data.map(d => [d.q, d.cost, d.p05, d.p95])]))}><Download size={15}/></button></div></section>;
}
export function SupplyLadder({ result }: { result: ScenarioResult }) {
  const max = Math.max(...result.supply.map(s => s.p95), 1);
  return <section className="card chart-card"><div className="chart-heading"><div><span className="eyebrow">WHERE YOUR CAPACITY COMES FROM</span><h2>The crowd supply ladder</h2></div><BarChart3 size={18} className="muted"/></div><p className="chart-description">Lower-cost tiers are used first. Bars show mean available deliveries.</p><div className="supply-ladder">{result.params.tiers.map((t, i) => <div className="supply-row" key={i}><div className="supply-label"><span className="tier-number">{i + 1}</span><span>{t.name}<small>R$ {num(t.unitCost, 1)} / delivery {t.unitCost < result.params.operatingCost && <b>· used first</b>}</small></span><strong>{num(result.supply[i].mean)}</strong></div><div className="supply-bar"><span style={{ width: `${result.supply[i].mean / max * 100}%`, background: t.unitCost < result.params.operatingCost ? '#7fa590' : '#d8b87d' }}/><div className="supply-whisker" style={{ left: `${result.supply[i].p05 / max * 100}%`, width: `${(result.supply[i].p95 - result.supply[i].p05) / max * 100}%` }}/></div></div>)}</div><div className="chart-foot"><span>Daily deliveries · whiskers: 5th–95th percentiles</span><span className="tiny-tag">FIG. 3 CONCEPT</span></div></section>;
}
export function DetailsCharts({ result }: { result: ScenarioResult }) {
  const components = [ ['Private capacity', result.cost.pdFixed.mean, '#3c8068'], ['Idle cost savings', -result.cost.idleSavings.mean, '#acc6b2'], ['Low-cost crowd', result.cost.cheapTierSpend.mean, '#dc9946'], ['Remaining crowd', result.cost.cdSpend.mean, '#d8b77d'], ['Unassigned penalty', result.cost.penalty.mean, '#bb6e63'] ] as const;
  const max = Math.max(...components.map(c => Math.abs(c[1])));
  const qmax = result.qStar.p95 * 1.2 || 1, step = Math.max(1, Math.ceil(qmax / 16 / 10) * 10), bins = Array.from({ length: Math.ceil(Math.max(...result.iterations.map(d => d.qStar)) / step) + 1 }, (_, i) => ({ q: i * step, count: 0 }));
  result.iterations.forEach(d => bins[Math.floor(d.qStar / step)].count++);
  return <><div className="two-charts"><section className="card chart-card"><div className="chart-heading"><div><span className="eyebrow">EVERY COST ACCOUNTED FOR</span><h2>A day, in costs</h2></div></div><div className="cost-components">{components.map(([label, value, c]) => <div key={label}><div><span>{label}</span><strong>{money(value)}</strong></div><div className="cost-track"><span style={{ width: `${Math.abs(value) / max * 100}%`, background: c }}/></div></div>)}</div><div className="total-row"><span>Average daily total · fixed hybrid</span><strong>{money(result.cost.total.mean)}</strong></div></section><section className="card chart-card"><div className="chart-heading"><div><span className="eyebrow">CONDITIONAL CAPACITY IN THIS IMPLEMENTATION</span><h2>Across supply realizations</h2></div><Info size={17} className="muted"/></div><p className="chart-description">Conditional Q* is recalculated for each supply draw. Its mean differs from a fixed fleet commitment.</p><div className="chart-container small"><ResponsiveContainer><BarChart data={bins} margin={{ top: 10, bottom: 20, left: 0, right: 10 }}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="q" tickLine={false} axisLine={false} fontSize={10} label={{ value: 'Conditional Q* (deliveries / day)', position: 'insideBottom', offset: -14, fontSize: 10 }}/><YAxis tickLine={false} axisLine={false} fontSize={10} width={38}/><Tooltip contentStyle={tip} labelFormatter={v => `Q* ${v}–${+v + step - 1}`} formatter={v => [v, 'Supply draws']}/><Bar dataKey="count" fill="#7b9d87" radius={[3, 3, 0, 0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div><div className="chart-foot"><span>Mean <b>{num(result.qStar.mean, 1)}</b> · SD {num(result.qStar.sd, 1)}</span><span>{num(result.iterations.length)} supply draws</span></div></section></div><details className="card inspector"><summary><div><ArrowUpRight size={17}/> Inspect the simulated days <span>First 50 observations</span></div><Download size={16}/></summary><p>Continuous capacity units are retained internally; the map visualizes batches. Costs include reliability adjustments.</p><button className="secondary-button" onClick={() => downloadIterations(result)}><Download size={15}/> Download all days as CSV</button><div className="table-scroll"><table><thead><tr>{['Day', 'Demand', 'Crowd slots', 'Conditional Q*', 'Fixed Q', 'PD allocated', 'CD allocated', 'Unassigned', 'Daily cost'].map(t => <th key={t}>{t}</th>)}</tr></thead><tbody>{result.iterations.slice(0, 50).map(d => <tr key={d.day}><td>{d.day}</td><td>{num(d.demand, 1)}</td><td>{num(d.supply.reduce((s, x) => s + x, 0), 1)}</td><td>{d.qStar}</td><td>{result.fixedQ}</td><td>{num(d.fixed.pd, 1)}</td><td>{num(d.fixed.cd, 1)}</td><td>{num(d.fixed.missed, 1)}</td><td>{money(d.fixed.total)}</td></tr>)}</tbody></table></div></details></>;
}
export function downloadIterations(r: ScenarioResult) {
  download('fleet-lab-simulated-days.csv', csv([['seed', 'convention', 'day', 'raw_demand', 'delivery_demand', ...r.params.tiers.map((_, i) => `tier_${i + 1}_supply`), 'conditional_q', 'fixed_q', 'pd_allocated', 'cd_allocated', 'unassigned', 'idle', 'pd_fixed', 'idle_savings', 'cheap_cd_spend', 'remaining_cd_spend', 'penalty', 'fixed_total', 'conditional_total', 'private_only_total', 'crowd_only_total'], ...r.iterations.map(d => [r.params.seed, r.params.convention, d.day, d.rawDemand, d.demand, ...d.supply, d.qStar, r.fixedQ, d.fixed.pd, d.fixed.cd, d.fixed.missed, d.fixed.idle, d.fixed.pdFixed, d.fixed.idleSavings, d.fixed.cheapTierSpend, d.fixed.cdSpend, d.fixed.penalty, d.fixed.total, d.conditional.total, d.pdOnly.total, d.cdOnly.total]) ]));
}
export { color, tip };
