import { ChevronDown, SlidersHorizontal, RotateCcw, Plus, Trash2, RefreshCw } from 'lucide-react';
import { DEFAULTS, PRESETS, paperParams } from '../../../packages/core/src';
import type { ScenarioParams } from '../../../packages/core/src';
import { num } from '../lib';

export function Slider({ label, value, min = 0, max, step = 0.02, onChange, help, suffix = '', decimals = 2, ends }: { label: string; value: number; min?: number; max: number; step?: number; onChange: (n: number) => void; help?: string; suffix?: string; decimals?: number; ends?: [string, string] }) {
  const id = label.toLowerCase().replaceAll(/[^a-z0-9]/g, '-');
  return <div className="slider-field"><div className="field-heading"><label htmlFor={id}>{label}</label><output htmlFor={id}>{num(value, decimals)}{suffix}</output></div>{help && <p className="field-help">{help}</p>}<input id={id} type="range" min={min} max={max} step={step} value={value} onChange={e => onChange(+e.target.value)} style={{ '--fill': `${(value - min) / (max - min) * 100}%` } as React.CSSProperties}/>{ends && <div className="range-ends"><span>{ends[0]}</span><span>{ends[1]}</span></div>}</div>;
}
export function NumberField({ label, value, onChange, step = 0.1, min = 0, max, unit }: { label: string; value: number; onChange: (n: number) => void; step?: number; min?: number; max?: number; unit?: string }) {
  return <label className="number-field"><span>{label}</span><div>{unit && <span>{unit}</span>}<input type="number" aria-label={label} value={value} step={step} min={min} max={max} onChange={e => onChange(e.target.value === '' ? 0 : +e.target.value)}/></div></label>;
}
export default function Controls({ params: p, setParams, presetName, setPresetName, saved, error }: { params: ScenarioParams; setParams: (p: ScenarioParams) => void; presetName: string; setPresetName: (s: string) => void; saved: ScenarioParams | null; error: string | null }) {
  const change = (patch: Partial<ScenarioParams>) => { setPresetName('Custom scenario'); setParams({ ...p, ...patch }); };
  const choose = (name: string) => { const preset = PRESETS.find(p => p.name === name); if (preset) setParams(paperParams(preset.patch)); else if (name === 'My saved scenario' && saved) setParams(saved); setPresetName(name); };
  return <aside className="controls card"><div className="panel-title"><div><SlidersHorizontal size={17}/><h2>Your scenario</h2></div><button className="icon-button" title="Reset to paper inputs" aria-label="Reset to paper inputs" onClick={() => choose(PRESETS[0].name)}><RotateCcw size={15}/></button></div>
    <div className="preset-select"><span className="eyebrow">START WITH A SCENARIO</span><div className="select-wrap"><select aria-label="Scenario preset" value={presetName} onChange={e => choose(e.target.value)}>{PRESETS.map(v => <option key={v.name}>{v.name}</option>)}{saved && <option>My saved scenario</option>}<option disabled>Custom scenario</option></select><ChevronDown size={15}/></div><span className="preset-description">{PRESETS.find(v => v.name === presetName)?.description ?? 'Explore a configuration of your own'}</span></div>
    <section className="control-section"><h3><span className="section-index">01</span> Delivery demand</h3><NumberField label="Average daily orders" value={p.demandMean} step={10} min={1} max={100000} onChange={demandMean => change({ demandMean })}/><Slider label="Demand variability" value={p.demandCV} max={1.5} help="How much order volume changes day to day." ends={['Predictable', 'Highly variable']} onChange={demandCV => change({ demandCV })}/></section>
    <section className="control-section"><h3><span className="section-index">02</span> Crowd availability</h3><Slider label="Supply variability" value={p.supplyCV} max={1.2} help="How much crowd capacity changes day to day." ends={['Steady supply', 'Uncertain supply']} onChange={supplyCV => change({ supplyCV })}/><Slider label="Supply synchronization" value={p.supplyCorrelation} max={1} step={0.05} help="The paper’s shared-supply mixing weight, ρ." ends={['Independent', 'Move together']} onChange={supplyCorrelation => change({ supplyCorrelation })}/></section>
    <section className="control-section"><h3><span className="section-index">03</span> Delivery economics</h3><div className="input-grid"><NumberField label="Private cost" unit="R$" value={p.pdUnitCost} min={0.01} onChange={pdUnitCost => change({ pdUnitCost })}/><NumberField label="Missed order" unit="R$" value={p.failedDeliveryCost} min={0.01} onChange={failedDeliveryCost => change({ failedDeliveryCost })}/></div><p className="field-help">Per delivery · includes reliability in expected costs.</p></section>
    <details className="advanced"><summary>Fleet & supply details <ChevronDown size={15}/></summary><div className="advanced-body"><NumberField label="Private operating cost" value={p.operatingCost} onChange={operatingCost => change({ operatingCost })} unit="R$"/><p className="field-help">Labor = R$ {num(p.pdUnitCost - p.operatingCost, 2)}. Idle capacity saves operating cost.</p><Slider label="Private reliability" value={p.pdReliability * 100} min={50} max={100} step={0.1} decimals={1} suffix="%" onChange={v => change({ pdReliability: v / 100 })}/><Slider label="Crowd reliability" value={p.cdReliability * 100} min={50} max={100} step={0.1} decimals={1} suffix="%" onChange={v => change({ cdReliability: v / 100 })}/><div className="tier-editor"><div className="tier-table-labels"><span>CD tier</span><span>R$/order</span><span>Capacity</span></div>{p.tiers.map((tier, i) => <div className="tier-inputs" key={i}><label><span className="sr-only">Tier {i + 1} name</span><input value={tier.name} onChange={e => change({ tiers: p.tiers.map((t, j) => j === i ? { ...t, name: e.target.value } : t) })}/></label><input aria-label={`${tier.name} unit cost`} type="number" min={0} step={0.1} value={tier.unitCost} onChange={e => change({ tiers: p.tiers.map((t, j) => j === i ? { ...t, unitCost: +e.target.value } : t) })}/><input aria-label={`${tier.name} capacity`} type="number" min={0.001} step={1} value={tier.meanCapacity} onChange={e => change({ tiers: p.tiers.map((t, j) => j === i ? { ...t, meanCapacity: +e.target.value } : t) })}/>{p.tiers.length > 2 && <button className="tier-remove" aria-label={`Remove ${tier.name}`} onClick={() => change({ tiers: p.tiers.filter((_, j) => i !== j) })}><Trash2 size={12}/></button>}</div>)}</div><p className="field-help">Capacities are deliveries per day, not drivers. Tier 5 uses Appendix S2.1’s 42.0.</p>{p.tiers.length < 8 && <button className="text-button" onClick={() => change({ tiers: [...p.tiers, { name: `Tier ${p.tiers.length + 1}`, unitCost: Math.min(p.failedDeliveryCost, p.tiers.at(-1)!.unitCost + 1), meanCapacity: 30 }] })}><Plus size={14}/> Add a supply tier</button>}<NumberField label="Shared supply mean" value={p.commonMeanCapacity} min={0.001} onChange={commonMeanCapacity => change({ commonMeanCapacity })}/><button className="text-button" onClick={() => change({ commonMeanCapacity: Math.round(p.tiers.reduce((s, t) => s + t.meanCapacity ** 2, 0) / p.tiers.reduce((s, t) => s + t.meanCapacity, 0) * 10) / 10 })}>Use capacity-weighted mean</button></div></details>
    <details className="advanced"><summary>Simulation settings <ChevronDown size={15}/></summary><div className="advanced-body"><label className="number-field"><span>Simulated days</span><select aria-label="Simulated days" value={p.iterations} onChange={e => change({ iterations: +e.target.value })}>{[100, 300, 1000, 3000, 10000].map(n => <option key={n} value={n}>{num(n)} days</option>)}</select></label><NumberField label="Random seed" value={p.seed} step={1} max={4294967295} onChange={seed => change({ seed })}/><button className="text-button" onClick={() => change({ seed: crypto.getRandomValues(new Uint32Array(1))[0] })}><RefreshCw size={13}/> Re-roll seed</button><label className="number-field"><span>Demand convention</span><select value={p.demandTruncation} onChange={e => change({ demandTruncation: e.target.value as ScenarioParams['demandTruncation'] })}><option value="zero">Normal · truncated at zero</option><option value="none">Normal · untruncated</option><option value="zeroAnd3Sigma">Normal · zero to μ + 3σ</option></select></label><label className="number-field"><span>Equation convention</span><select value={p.convention} onChange={e => change({ convention: e.target.value as ScenarioParams['convention'] })}><option value="paper">Appendix-based reconstruction</option><option value="legacyJava">Java convention diagnostic</option></select></label><NumberField label="Private-only buffer (σ)" value={p.pdOnlyZ} min={0} max={4} step={0.01} onChange={pdOnlyZ => change({ pdOnlyZ })}/><p className="field-help">Default private-only capacity: μ + 2.33σ. The paper does not specify this rule.</p><button className="text-button" onClick={() => { setParams(paperParams()); setPresetName(PRESETS[0].name); }}>Restore all paper inputs</button></div></details>
    {error && <div className="inline-error" role="alert">{error}</div>}
    <div className="control-footnote"><span className="status-dot"/> Runs locally in your browser <span>Seed {p.seed === DEFAULTS.seed ? '42' : p.seed}</span></div>
  </aside>;
}
