import { useEffect, useMemo, useReducer, useRef, useState } from 'react';
import { Activity, ArrowDownRight, ArrowRight, BookOpen, Check, ChevronRight, Download, FlaskConical, Layers3, Link2, Moon, Save, Sun, Truck, X } from 'lucide-react';
import { customPolicy, normalizeParams, paperParams, PRESETS } from '../../packages/core/src';
import type { ScenarioParams, ScenarioResult } from '../../packages/core/src';
import Controls, { Slider } from './components/Controls';
import Simulation from './components/Simulation';
import { CostCurve, DetailsCharts, downloadIterations, SupplyLadder } from './components/Charts';
import Experiments from './components/Experiments';
import Research from './components/Research';
import { loadInitial, money, num, pct, sourceUrl } from './lib';

type Tab = 'sandbox' | 'experiments' | 'research' | 'methodology';
const initial = loadInitial();
export default function App() {
  const [params, setParams] = useReducer((_: ScenarioParams, p: ScenarioParams) => p, initial.params);
  const [presetName, setPresetName] = useState(new URLSearchParams(location.search).has('scenario') ? 'Custom scenario' : PRESETS[0].name);
  const [result, setResult] = useState<ScenarioResult | null>(null), [busy, setBusy] = useState(true), [error, setError] = useState<string | null>(null);
  const [tab, setTab] = useState<Tab>('sandbox'), [policy, setPolicy] = useState('hybrid'), [customQ, setCustomQ] = useState(350), [day, setDay] = useState(0);
  const [toast, setToast] = useState<string | null>(initial.notice ?? null), [experimentStart, setExperimentStart] = useState<'base' | 'correlation' | 'failure' | 'fleets'>('base');
  const [dark, setDark] = useState(() => { try { return (localStorage.getItem('fleet-theme') ?? (matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light')) === 'dark'; } catch { return false; } });
  const [saved, setSaved] = useState<ScenarioParams | null>(() => { try { const p = localStorage.getItem('fleet-scenario'); return p ? normalizeParams(JSON.parse(p)) : null; } catch { return null; } });
  const worker = useRef<Worker | null>(null);
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; try { localStorage.setItem('fleet-theme', dark ? 'dark' : 'light'); } catch { /* Browser storage may be disabled. */ } }, [dark]);
  useEffect(() => {
    worker.current?.terminate(); setBusy(true); setError(null);
    const timer = setTimeout(() => {
      try { normalizeParams(params); } catch (e) { setError((e as Error).message); setBusy(false); return; }
      const w = new Worker(new URL('./workers/sim.worker.ts', import.meta.url), { type: 'module' }); worker.current = w;
      w.onmessage = e => { if (e.data.kind === 'result') { setResult(e.data.result); setDay(0); setBusy(false); } else if (e.data.kind === 'error') { setError(e.data.message); setBusy(false); } };
      w.onerror = () => { setError('The simulation worker could not start. Reload this page from the development server.'); setBusy(false); };
      w.postMessage({ kind: 'scenario', params });
    }, 250);
    return () => { clearTimeout(timer); worker.current?.terminate(); };
  }, [params]);
  useEffect(() => { if (!toast) return; const t = setTimeout(() => setToast(null), 6000); return () => clearTimeout(t); }, [toast]);
  const custom = useMemo(() => result && policy === 'custom' ? customPolicy(result, customQ) : null, [result, policy, customQ]);
  const chosen = custom ?? result?.policies.find(p => p.key === policy) ?? result?.policies[0];
  const currentDay = result ? Math.min(day, result.iterations.length - 1) : 0;
  const allocation = result ? policy === 'custom' ? custom!.allocations[currentDay] : policy === 'pdOnly' ? result.iterations[currentDay].pdOnly : policy === 'cdOnly' ? result.iterations[currentDay].cdOnly : result.iterations[currentDay].fixed : null;
  const share = async () => {
    try { normalizeParams(params); const url = new URL(location.href); url.search = ''; url.searchParams.set('scenario', JSON.stringify(params)); await navigator.clipboard.writeText(url.toString()); history.replaceState(null, '', url); setToast('Scenario link copied. Every model parameter and the seed are included.'); } catch { setToast('Could not copy a link. Check your inputs and browser clipboard permissions.'); }
  };
  const save = () => { try { const p = normalizeParams(params); localStorage.setItem('fleet-scenario', JSON.stringify(p)); setSaved(p); setToast('Scenario saved on this device. Find it in the preset menu.'); } catch (e) { setToast(`Could not save: ${(e as Error).message}`); } };
  const showProposition = (n: number) => { setParams(paperParams(n === 2 ? { supplyCV: 0.8 } : n === 3 ? { supplyCV: 0.4, supplyCorrelation: 0.5 } : n === 4 ? { failedDeliveryCost: 41.6 } : {})); setPresetName('Custom scenario'); setExperimentStart(n === 3 ? 'correlation' : n === 4 ? 'failure' : n === 5 ? 'fleets' : 'base'); setTab('experiments'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const tabs: { id: Tab; text: string; icon: typeof Activity }[] = [{ id: 'sandbox', text: 'Fleet sandbox', icon: Activity }, { id: 'experiments', text: 'Experiments', icon: FlaskConical }, { id: 'research', text: 'The research', icon: BookOpen }];
  return <><header className="app-header"><a className="brand" href="#" onClick={e => { e.preventDefault(); setTab('sandbox'); }}><span className="brand-mark"><Layers3 size={23}/></span><span>fleet<span className="brand-light">lab</span><small>THE SCIENCE OF LAST-MILE DELIVERY</small></span></a><nav aria-label="Main navigation">{tabs.map(t => <button key={t.id} className={tab === t.id || tab === 'methodology' && t.id === 'research' ? 'nav-tab selected' : 'nav-tab'} onClick={() => setTab(t.id)}><t.icon size={15}/>{t.text}</button>)}</nav><div className="header-actions"><a className="paper-link" href={sourceUrl} target="_blank" rel="noreferrer">Read the paper <ArrowRight size={14}/></a><span className="header-divider"/><button className="icon-button" title={dark ? 'Switch to light theme' : 'Switch to dark theme'} aria-label={dark ? 'Switch to light theme' : 'Switch to dark theme'} onClick={() => setDark(!dark)}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</button></div></header>
    <main><div className="page-heading"><div><div className="breadcrumb">RESEARCH, IN MOTION <span>/</span> TWO-SIDED UNCERTAINTY</div><h1>{tab === 'sandbox' ? <>A smarter mix. <em>A stronger fleet.</em></> : tab === 'experiments' ? <>One model. <em>Many possibilities.</em></> : tab === 'methodology' ? <>Inside <em>the model.</em></> : <>The science behind <em>the fleet.</em></>}</h1><p>{tab === 'sandbox' ? 'Balance a dependable private fleet with a flexible crowd. See what uncertainty changes.' : tab === 'experiments' ? 'Explore how demand, supply, and delivery costs change the capacity decision.' : 'An interactive companion to Last Mile Delivery Capacity Planning with Two-Sided Uncertainty.'}</p></div>{tab === 'sandbox' && <div className="page-actions"><button className="secondary-button" onClick={save}><Save size={15}/> Save scenario</button><button className="primary-button" onClick={share}><Link2 size={15}/> Share scenario</button></div>}</div>
      {tab === 'sandbox' ? <div className="sandbox-layout"><Controls params={params} setParams={setParams} presetName={presetName} setPresetName={setPresetName} saved={saved} error={error}/><div className="results" aria-busy={busy}>
        <div className="results-topline"><div className="mode-label"><span className="status-dot"/>{error ? 'Showing the last valid result' : busy ? 'Recalculating your scenario…' : 'Your scenario results'}<span className="run-meta">{result ? `${num(result.iterations.length)} simulated days · seed ${result.params.seed}` : 'Preparing the model'}</span></div><button className="text-button" onClick={() => setTab('methodology')}>How it works <ChevronRight size={14}/></button></div>
        {busy && <div className="loading-line"/>}
        {result && chosen && allocation ? <><div className="metric-grid"><div className="metric-card recommendation"><div className="metric-label">FIXED-PLANNING ESTIMATE <Truck size={17}/></div><div className="metric-value">{num(result.fixedQ)}<span>deliveries / day</span></div><div className="metric-caption"><span className="recommend-dot"/> App extension · chosen before the day</div></div><div className="metric-card"><div className="metric-label">EXPECTED DAILY COST <span>R$</span></div><div className="metric-value"><small>R$</small> {num(chosen.cost.mean)}</div><div className="metric-caption">{money(chosen.cost.mean / Math.max(chosen.demand, 1))} per order · {policy === 'custom' ? 'custom fleet' : policy === 'hybrid' ? 'hybrid fleet' : policy === 'pdOnly' ? 'private only' : 'crowd only'}</div></div><div className="metric-card"><div className="metric-label">CAPACITY COVERAGE <PackageIcon/></div><div className="metric-value">{num((1 - chosen.missed / Math.max(chosen.demand, 1)) * 100, 1)}<small>%</small></div><div className="metric-caption">{num(chosen.missed, 1)} orders / day without capacity</div></div></div>
        <div className="policy-strip"><div><strong>Choose your fleet strategy</strong><span>Same demand. Same supply. A different mix.</span></div><div className="segmented" role="group" aria-label="Fleet strategy">{[['hybrid', 'Hybrid'], ['pdOnly', 'Private only'], ['cdOnly', 'Crowd only'], ['custom', 'Your mix']].map(([id, text]) => <button key={id} aria-pressed={policy === id} className={policy === id ? 'active' : ''} onClick={() => setPolicy(id)}>{id === 'hybrid' && <Layers3 size={13}/>} {text}</button>)}</div></div>
        {policy === 'custom' && <div className="card custom-capacity"><Slider label="Your private capacity" value={customQ} max={Math.ceil((params.demandMean + params.demandCV * params.demandMean * 4) / 100) * 100} step={1} decimals={0} onChange={setCustomQ} help="Commit this many private delivery slots before demand and crowd supply are observed."/></div>}
        <Simulation result={result} policy={policy} day={currentDay} setDay={setDay} allocation={allocation}/>
        <div className="insight-banner"><div className="insight-icon"><Layers3 size={20}/></div><div><strong>Low unit cost is only part of the story.</strong><p>Crowd deliveries average {money(result.avgExpectedCdUnitCost, 1)} each; private capacity costs {money(result.expectedPdUnitCost, 1)}. The fleet decision also accounts for uncertain availability, idle capacity, and missed orders.</p></div><button className="icon-button" aria-label="Read the research insight" onClick={() => setTab('research')}><ArrowUpRightIcon/></button></div>
        {result.warnings.length > 0 && <details className="model-warning"><summary>{result.warnings.length} model note{result.warnings.length > 1 ? 's' : ''} for this scenario</summary>{result.warnings.map(w => <p key={w}>{w}</p>)}</details>}
        <div className="section-heading"><div><span className="eyebrow">BEYOND A SINGLE DAY</span><h2>Understand the trade-offs</h2></div><button className="text-button" onClick={() => downloadIterations(result)}><Download size={14}/> Export results</button></div>
        <div className="policy-comparison">{result.policies.map((p, i) => <button key={p.key} className={`card policy-card ${policy === p.key ? 'selected' : ''}`} onClick={() => setPolicy(p.key)}><span>{p.name}{i === 0 && <span className="tiny-tag">APP EXTENSION</span>}</span><strong>{money(p.cost.mean)}<small>/ day</small></strong><div className="allocation-bar"><i className="pd" style={{ width: `${p.pd / p.demand * 100}%` }}/><i className="cd" style={{ width: `${p.cd / p.demand * 100}%` }}/><i className="missed" style={{ width: `${p.missed / p.demand * 100}%` }}/></div><div className="policy-note">{pct((p.pd + p.cd) / p.demand)} capacity coverage · {num(p.q)} private slots</div><div className="ci-note">95% cost CI: {money(p.cost.ci95[0])}–{money(p.cost.ci95[1])}</div></button>)}</div>
        <div className="two-charts"><CostCurve result={result} selectedQ={chosen.q}/><SupplyLadder result={result}/></div><DetailsCharts result={result}/><div className="replication-note"><BookOpen size={16}/><p>This browser reconstruction is still being validated against the published results. <button onClick={() => setTab('methodology')}>See the implementation audit.</button></p></div></> : <div className="card skeleton"><div/><div/><p>Drawing demand and supply, then finding the capacity balance…</p></div>}
      </div></div> : tab === 'experiments' ? <Experiments params={params} initialExperiment={experimentStart} onLoad={(patch) => { setParams({ ...params, ...patch }); setPresetName('Custom scenario'); setTab('sandbox'); }}/>: <Research methodology={tab === 'methodology'} onMethodology={() => setTab(tab === 'methodology' ? 'research' : 'methodology')} onShow={showProposition}/>}
    </main><footer className="app-footer"><span><Layers3 size={16}/> Based on Castillo, Posner, Sodero, and Zinn · Journal of Business Logistics</span><div><span>Research demonstration · v1.0</span><button onClick={() => setTab('methodology')}>Model & assumptions <ChevronRight size={13}/></button></div></footer>{toast && <div role="status" className="toast"><Check size={17}/><span>{toast}</span><button className="icon-button" aria-label="Dismiss notification" onClick={() => setToast(null)}><X size={15}/></button></div>}</>;
}
function PackageIcon() { return <Check size={17}/>; }
function ArrowUpRightIcon() { return <ArrowDownRight size={19} style={{ transform: 'rotate(-90deg)' }}/>; }
