import { mkdirSync, writeFileSync } from 'node:fs';
import { findQ, normalCdf, paperParams, prepare, sampleDraw } from '../packages/core/src/index';

const cases = [
  { demandCV: .2, supplyCV: .2 },
  { demandCV: .2, supplyCV: .8 },
  { demandCV: .8, supplyCV: .2 },
  { demandCV: .8, supplyCV: .8 },
  { demandCV: .34, supplyCV: .36 },
];
const rows = [];
for (const seed of [42, 123, 2026]) for (const settings of cases) {
  const params = paperParams({ ...settings, seed }), model = prepare(params);
  const supplies = Array.from({ length: 1000 }, (_, k) => sampleDraw(model, k).supply);
  const meanQ = (variant: typeof model) => supplies.reduce((sum, supply) => sum + findQ(variant, [supply]), 0) / supplies.length;
  rows.push({ ...settings, seed,
    defaultCosts: meanQ(model),
    rawCostThreshold: meanQ({ ...model, rhs: (params.failedDeliveryCost - params.pdUnitCost) / (params.failedDeliveryCost - params.operatingCost) }),
    untruncatedCdf: meanQ({ ...model, cdf: x => normalCdf((x - params.demandMean) / (params.demandMean * params.demandCV)) }),
    javaCosts: meanQ(prepare({ ...params, convention: 'legacyJava', demandTruncation: 'zeroAnd3Sigma' })),
  });
}
const table = rows.map(r => `| ${r.demandCV} | ${r.supplyCV} | ${r.seed} | ${r.defaultCosts.toFixed(2)} | ${r.rawCostThreshold.toFixed(2)} | ${r.untruncatedCdf.toFixed(2)} | ${r.javaCosts.toFixed(2)} |`).join('\n');
const report = `# Fleet Lab calculation settings

Generated by \`npm run compare-settings\`. These examples illustrate calculation settings within the browser app. Each row uses the same 1,000 sampled supply vectors across its four settings and reports mean conditional capacity in deliveries per day.

| Demand CV | Supply CV | Seed | Default costs | Raw-cost threshold | Untruncated demand CDF | Java cost setting |
| --- | --- | --- | --- | --- | --- | --- |
${table}

## Settings

- **Default costs:** the app's reliability-adjusted costs and default demand distribution.
- **Raw-cost threshold:** total private unit cost in the threshold, retaining the other default settings.
- **Untruncated demand CDF:** an untruncated normal CDF in the capacity calculation, retaining the default costs.
- **Java cost setting:** raw costs, a zero initial threshold baseline, all crowd tiers in the capacity ladder, and demand bounded by zero and μ + 3σ.

The sandbox exposes calculation and demand settings under **Simulation settings**. The fixed fleet planning extension is described in \`DECISIONS.md\`.
`;
mkdirSync('app/public/sources', { recursive: true });
writeFileSync('CALCULATION_SETTINGS.md', report);
writeFileSync('app/public/sources/CALCULATION_SETTINGS.md', report);
console.log('App calculation examples written to CALCULATION_SETTINGS.md.');
