import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';

const result = spawnSync(process.execPath, ['node_modules/vitest/vitest.mjs', 'run'], { stdio: 'inherit' });
if (result.error) throw result.error;
const passed = result.status === 0;
const checks = [{ label: 'Fleet Lab software test suite', command: 'npm test', status: passed ? 'PASS' : 'FAIL' }];
const report = `# Fleet Lab software checks

Generated by \`npm run validate\`. This report records automated checks of the browser app's software.

| Check | Command | Status |
| --- | --- | --- |
| Numerical routines and simulation behavior | npm test | ${passed ? 'PASS' : 'FAIL'} |

The suite in \`packages/core/test/model.test.ts\` covers:

- Normal distribution reference probabilities and Beta sampling.
- Seeded random streams and repeatable scenario results.
- Cost calculations, input bounds, and supply settings.
- Capacity search and allocation conservation.
- Demand integration and fixed fleet cost curves.
- Fleet comparisons on common demand and supply draws.
- Experiment design sizes and finite scenario outputs.

Run \`npm run test:coverage\` for a coverage report and \`npm run build\` for the production TypeScript and static-site build. Browser checks are recorded in \`QA.md\`.
`;
mkdirSync('app/public/precomputed', { recursive: true });
mkdirSync('app/public/sources', { recursive: true });
writeFileSync('VALIDATION.md', report);
writeFileSync('app/public/precomputed/validation.json', JSON.stringify(checks));
copyFileSync('VALIDATION.md', 'app/public/sources/VALIDATION.md');
console.log(`Fleet Lab software tests: ${passed ? 'PASS' : 'FAIL'}. Report: VALIDATION.md`);
process.exitCode = result.status ?? 1;
